version: '3.6'

services:
  angular_01_dev:
    container_name: angular_01_dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
    - ./src:/app/src
    - ./package.json:/app/package.json
    - ./package-lock.json:/app/package-lock.json
    ports:
    - 4200:4200
